# Generated by Django 5.0.1 on 2024-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_photo', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('hosting_church_or_group', models.CharField(max_length=255)),
                ('church_location', models.CharField(max_length=255)),
                ('church_district', models.CharField(max_length=255)),
                ('church_conference', models.CharField(max_length=255)),
                ('website_link', models.CharField(max_length=255)),
                ('church_facebook', models.CharField(max_length=255)),
                ('church_instagram', models.CharField(max_length=255)),
                ('church_twitter', models.CharField(max_length=255)),
                ('speaker_name', models.CharField(max_length=50)),
                ('speaker_title', models.CharField(max_length=50)),
                ('speaker_image', models.ImageField(upload_to='')),
                ('sessions_activities', models.FileField(upload_to='')),
                ('on_site', models.BooleanField()),
                ('sponsor_title', models.CharField(max_length=50)),
                ('sponsor_logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('author', models.CharField(default='Unknown', max_length=50)),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
