# Generated by Django 5.0.1 on 2024-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventcomment_rename_news_newspost_newspostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
