# Generated by Django 5.0.1 on 2024-01-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newspostcomment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspostcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
