# Generated by Django 5.0.1 on 2024-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newspostcomment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
                ('category_slug', models.SlugField()),
            ],
            options={
                'ordering': ('-category_title',),
            },
        ),
        migrations.DeleteModel(
            name='NewsPostComment',
        ),
    ]
