# Generated by Django 5.0.1 on 2024-01-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_options_event_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=20),
        ),
    ]
