# Generated by Django 5.0.1 on 2024-01-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_event_photo_alter_event_speaker_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='church_facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='church_instagram',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='church_twitter',
            new_name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sessions_activities',
        ),
    ]
