# Generated by Django 5.0.1 on 2024-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_church_facebook_event_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(upload_to='uploads/events'),
        ),
    ]
